# project name
name: 'dbt_servian_demo'
version: '1.0.0'

config-version: 2

# should match the profile name defined in profiles.yml file
profile: 'default'

# These configurations specify where dbt should look for different types of files.
source-paths: ["models"] # sql statments
test-paths: ["tests"] # tests
data-paths: ["data"] # data
macro-paths: ["macros"]
target-path: "target"  # directory which will store compiled SQL files


# models (SQL to run)
models:
  dbt_servian_demo: #must match the profile name defined above
      staging: #matches the model/staging
          +materialized: table # type of materialization
          +schema: staging
