default:
  outputs:
    dev:
      type: bigquery 
      method: oauth
      project: graham-hamza-bq-dbt-webinar
      dataset: staging
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive
      retries: 1
  target: dev


